permissions:
  contents: write

name: Auto Update Data

on:
  schedule:
    - cron: '*/2 * * * *'
  repository_dispatch:
    types:
      - form_submitted

jobs:
  update:
    runs-on: ubuntu-latest

    # ジョブ全体に渡したい環境変数
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      PEPPER:         ${{ secrets.PEPPER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Generate Data & Auth
        run: python -u update_all.py

      - name: Commit CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions
