permissions:
contents: write

name: Auto Update Data

on:
repository\_dispatch:
types: \[form\_submitted]
schedule:
\- cron: '\*/15 \* \* \* \*'
workflow\_dispatch: {}

jobs:
basic\_update:
name: Light Data Update
runs-on: ubuntu-latest
if: github.event\_name == 'repository\_dispatch'
env:
SPREADSHEET\_ID: \${{ secrets.SPREADSHEET\_ID }}
PEPPER:         \${{ secrets.PEPPER }}
steps:
\- name: Checkout repository
uses: actions/checkout\@v3
with:
persist-credentials: true
fetch-depth: 0

```
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Authenticate to Google Cloud
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

  - name: Light data update
    run: python -u update_all.py --light

  - name: Sync with remote
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git stash
      git pull origin main --rebase
      git stash pop

  - name: Commit light CSVs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      git add \
        responses.csv \
        auth.csv \
        initial_assignment_result.csv \
        assignment_with_unanswered.csv \
        probability_montecarlo_combined.csv \
        popular_departments_rank_combined.csv \
        popular_departments_rank_by_term.csv \
        assignment_matrix.csv \
        department_summary.csv
      git commit -m "chore: light data update [skip ci]" || echo "No changes to commit"
      git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
```

first\_choice\_sim:
name: First-Choice Precompute
runs-on: ubuntu-latest
if: github.event\_name == 'schedule' || github.event\_name == 'workflow\_dispatch'
steps:
\- name: Checkout repository
uses: actions/checkout\@v3
with:
fetch-depth: 0

```
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Generate First Choice Probabilities
    run: python simulate_each_as_first.py

  - name: Sync with remote
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git stash
      git pull origin main --rebase
      git stash pop

  - name: Commit first-choice CSV
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      git add first_choice_probabilities.csv
      git commit -m "chore: first-choice precompute [skip ci]" || echo "No changes to commit"
      git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
```
